swagger: "2.0"

info:
  version: "1.0"
  title: "Hello World API"

# basePath: /v2

paths:
  /:
    get:
      x-cdk-lambda-code: ./dist
      x-cdk-lambda-handler: example.handler
      x-cdk-lambda-name: helloWorldGetLambda
      description: Returns a greeting to the user!
      produces:
        - application/json
      # parameters:
      # - in: query
      #   name: test
      #   type: string
      #   description: The test
      responses:
        200:
          description: Returns the greeting.
          schema:
            type: object
  /cache: # /cache/3/
    get:
      x-cdk-lambda-code: ./dist
      x-cdk-lambda-handler: example.handler
      x-cdk-lambda-name: helloCacheGetLambda
      description: Returns a greeting to the user!
      # parameters:
      # - in: query
      #   name: test
      #   type: string
      #   description: The test
      responses:
        200:
          description: Returns the greeting.
          schema:
            type: string