swagger: "2.0"

info:
  version: "1.0"
  title: "Hello World API"

# basePath: /v2

paths:
  /:
    get:
      x-cdk-lambda-handler: ./users/index.handler # 실행이 되는 핸들러 파일
      x-cdk-additional-library: [md5]
      description: Returns a greeting to the user!
      produces:
        - application/json
      # parameters:
      # - in: query
      #   name: test
      #   required: true
      #   type: integer
      #   description: The test
      responses:
        200:
          description: Returns the greeting.
          schema:
            type: object
    post:
      x-cdk-lambda-handler: ./cache.handler # 실행이 되는 핸들러 파일
      description: Returns a greeting to the user!
      produces:
        - application/json
      # parameters:
      # - in: body
      #   name: user
      #   description: The user to create.
      #   schema:
      #     type: object
      #     required:
      #       - userName
      #       - firstName
      #     properties:
      #       userName:
      #         type: string
      #       firstName:
      #         type: string
      #       lastName:
      #         type: string
      responses:
        200:
          description: Returns the greeting.
          schema:
            type: object
  /cache/{user_id}/sensor:
    get:
      x-cdk-lambda-handler: example.handler2
      description: Returns a greeting to the user!
      # parameters:
      # - in: query
      #   name: test
      #   type: string
      #   description: The test
      responses:
        200:
          description: Returns the greeting.
          schema:
            type: string